### ISSUE TITLE
It didnt work when i used it

### ISSUE THREAD

**Issue by AutumnEviening** [WEGFan/Geometry-Dash-Savefile-Fix#10]
About a year ago my game broke and didn't work then my friend sent me this and it worked but today I used it again because my game broke but it didn't work this time.  I have verified my game files, deleted Mega-Hack and BetterEdit and it still doesn't work. GD opens, White Screens then closes.

**Comment by WEGFan** [comment]
Does the game open if you move save files out of your save file folder? If it still doesn
t, it's not the save files causing the problem, and you'd better ask for help in GD servers.

**Comment by AutumnEviening** [comment]
I got it to work after a bit, idk what I did but it was a fault on my end,
Sorry
