### ISSUE TITLE
OMG THANKS!

### ISSUE THREAD

**Issue by zpatten** [WEGFan/Geometry-Dash-Savefile-Fix#15]
My son just had his GD saves get corrupted and none of the usual tricks where working (including trying to use the "backup" versions of the GD files).  He has around 550 hours in the game at this point and I was getting worried all that progress was lost.  After a bit of google engineering I thankfully found this.

Thanks to your script here I was able to recover those files for him; no idea how you figured this out but thanks a million; you saved my son from a devastating situation of losing all that work.

As a caution to others who read this; counter to my assumptions, there is no steam (or apparently any other?) cloud backup for GD save data.  Definitely seems like a good idea to backup the GD localdata files regularly to avoid losing everything.

**Comment by WEGFan** [comment]
You can also register an account ingame and use cloud save feature from it (and it's cross-platform)
