### ISSUE TITLE
potential bug?

### ISSUE THREAD

**Issue by TheTechRobo** [WEGFan/Geometry-Dash-Savefile-Fix#5]
i don't have time to test, but https://github.com/WEGFan/Geometry-Dash-Savefile-Fix/blob/master/GDSavefileFix.py#L45 looks a bit odd. 

`print(f'Savefiles backed up to {SAVEFILE_PATH / backup_folder_name}')`

Shouldn't thst be `print(f'Savefiles backed up to {SAVEFILE_PATH} / {backup_folder_name}')`? Otherwise it's dividing SAVEFILE_PATH by backup_folder_name, isn't it?

**Comment by WEGFan** [comment]
This is `Path` from `pathlib` package, and you can merge two paths together by `/`, this is an example from the [document](https://docs.python.org/3/library/pathlib.html)

```python
>>> p = Path('/etc')
>>> q = p / 'init.d' / 'reboot'
>>> q
PosixPath('/etc/init.d/reboot')
>>> q.resolve()
PosixPath('/etc/rc.d/init.d/halt')
```

**Comment by TheTechRobo** [comment]
oh, sorry. Must not have read it properly.
