### ISSUE TITLE
It isn't working

### ISSUE THREAD

**Issue by jhlzhyjpwoly** [WEGFan/Geometry-Dash-Savefile-Fix#6]
I have no idea when my files got corrupted, but they stopped working this morning. I tried this, put the fixed files back in the gd folder and it did nothing. I still get the simple message that the game is launching, and it won't open. If anyone has any idea as to why this is happening, it would be greatly appreciated, for I am working on a part in a collab and absolutely cannot lose it.

**Comment by WEGFan** [comment]
will the game open if you move your save files to somewhere and leave the folder empty?
