### ISSUE TITLE
issue fixing

### ISSUE THREAD

**Issue by Friksis12** [WEGFan/Geometry-Dash-Savefile-Fix#8]
![image](https://user-images.githubusercontent.com/94933787/143243679-1d097d14-a225-48d2-99e5-c5156c4a9722.png)
Srr if this seems very dumb but I know nothing about coding and something that involves coding. And if you can help please help.

**Comment by WEGFan** [comment]
Could you send your savefiles to my discord? (WEGFan#1440)

**Comment by Friksis12** [comment]
Alright I added you.
