### ISSUE TITLE
It's not working

### ISSUE THREAD

**Issue by Hemzy529** [WEGFan/Geometry-Dash-Savefile-Fix#9]
Worked fine 2 or 3 times before, but now saves broke again (as always no idea why) and after it "fixes" them gd still doesnt launch. The issue is definetly saves cuz when i remove them from saves folder gd launches fine

**Comment by WEGFan** [comment]
When the save file gets some specific sizes, the game won't launch, maybe try to run the program multiple times and see if the game opens?

**Comment by Hemzy529** [comment]
Doesnt help. CCGameManager is around 60mb and CCLocalLevels is around 70mb and the program doesnt do anything to their size, gd still doesnt open

**Comment by WEGFan** [comment]
hmmm, then maybe it's because your save files are too big so the game can't handle that much data, maybe you can use 4gb patch to patch the game and increase its memory limit

**Comment by Hemzy529** [comment]
I already use 4gb patch

**Comment by WEGFan** [comment]
if you only remove CCLocalLevels from your saves folder, can the game open? if it opens, you need to delete some saved levels to decrease the size of CCGameManager

**Comment by Hemzy529** [comment]
This didnt work either (the game still didnt open) but i also tried removing both saves and it literally did nothing. As a conclusion - i am stupid, the problem was the BetterEdit save file (i removed it with other save files when i tested if the issue is saves or smth else). Sorry for wasting your time lol
